# PURL configuration for http://purl.obolibrary.org/obo/app

idspace: APP
base_url: /obo/app

products:
- app.owl: https://raw.githubusercontent.com/nkauxue/apples/master/app.owl
- app.obo: https://raw.githubusercontent.com/nkauxue/apples/master/app.obo

term_browser: ontobee
example_terms:
- APP_0000000

entries:

- prefix: /releases/
  replacement: https://raw.githubusercontent.com/nkauxue/apples/v

- prefix: /tracker/
  replacement: https://github.com/nkauxue/apples/issues

- prefix: /about/
  replacement: http://www.ontobee.org/ontology/APP?iri=http://purl.obolibrary.org/obo/

## generic fall-through, serve direct from github by default
- prefix: /
  replacement: https://raw.githubusercontent.com/nkauxue/apples/master/
